server:
  port: '8080'

spring:
  profiles:
    active: dev


---

spring:
  profiles: dev
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:gustavo-dev
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    management:
      endpoints:
        web:
          exposure:
            include: "*"

---

spring:
  profiles: qa
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:gustavo-qa
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  management:
    endpoints:
      web:
        exposure:
          include: "*"



---

spring:
  profiles: prod
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:gustavo-prod
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


